/**
 * Explicit Telegram bot screens + deterministic Back parents.
 * Home always resolves to role root (USER_ROOT | ADMIN_ROOT).
 */

export const BotScreen = {
  USER_ROOT: 'USER_ROOT',
  USER_BUY_STANDARD: 'USER_BUY_STANDARD',
  USER_BUY_PERIOD: 'USER_BUY_PERIOD',
  USER_BUY_PAYMENT_METHOD: 'USER_BUY_PAYMENT_METHOD',
  USER_BUY_PAYMENT_SUMMARY: 'USER_BUY_PAYMENT_SUMMARY',
  USER_BUY_PENDING_REENTRY: 'USER_BUY_PENDING_REENTRY',
  AWAITING_PAYMENT_RECEIPT: 'AWAITING_PAYMENT_RECEIPT',
  USER_CANCEL_PAYMENT_CONFIRM: 'USER_CANCEL_PAYMENT_CONFIRM',
  USER_LICENSES_LIST: 'USER_LICENSES_LIST',
  USER_LICENSE_DETAIL: 'USER_LICENSE_DETAIL',
  USER_LICENSE_DEVICES: 'USER_LICENSE_DEVICES',
  USER_DEVICE_DETAIL: 'USER_DEVICE_DETAIL',
  USER_DEVICE_DISCONNECT_CONFIRM: 'USER_DEVICE_DISCONNECT_CONFIRM',
  USER_RECOVERY_INSTRUCTION: 'USER_RECOVERY_INSTRUCTION',
  USER_LANGUAGE: 'USER_LANGUAGE',
  USER_SUPPORT_CATEGORY: 'USER_SUPPORT_CATEGORY',
  SUPPORT_ACTIVE: 'SUPPORT_ACTIVE',
  USER_SUPPORT_CLOSE_CONFIRM: 'USER_SUPPORT_CLOSE_CONFIRM',
  USER_INSTRUCTION_ROOT: 'USER_INSTRUCTION_ROOT',
  USER_INSTRUCTION_ARTICLE: 'USER_INSTRUCTION_ARTICLE',

  ADMIN_ROOT: 'ADMIN_ROOT',
  ADMIN_ORDERS_LIST: 'ADMIN_ORDERS_LIST',
  ADMIN_ORDER_DETAIL: 'ADMIN_ORDER_DETAIL',
  ADMIN_ORDER_APPROVE_CONFIRM: 'ADMIN_ORDER_APPROVE_CONFIRM',
  ADMIN_ORDER_REJECT_CONFIRM: 'ADMIN_ORDER_REJECT_CONFIRM',
  ADMIN_ORDER_REJECT_REASON: 'ADMIN_ORDER_REJECT_REASON',
  ADMIN_PAYMENT_METHODS_LIST: 'ADMIN_PAYMENT_METHODS_LIST',
  ADMIN_PAYMENT_METHOD_DETAIL: 'ADMIN_PAYMENT_METHOD_DETAIL',
  ADMIN_PAYMENT_METHOD_EDIT: 'ADMIN_PAYMENT_METHOD_EDIT',
  ADMIN_SUPPORT_LIST: 'ADMIN_SUPPORT_LIST',
  ADMIN_SUPPORT_CONVERSATION: 'ADMIN_SUPPORT_CONVERSATION',
  ADMIN_SUPPORT_REPLY: 'ADMIN_SUPPORT_REPLY',
  ADMIN_SUPPORT_CLOSE_CONFIRM: 'ADMIN_SUPPORT_CLOSE_CONFIRM',
  ADMIN_LICENSES_LIST: 'ADMIN_LICENSES_LIST',
  ADMIN_LICENSE_DETAIL: 'ADMIN_LICENSE_DETAIL',
  ADMIN_LICENSE_DEVICES: 'ADMIN_LICENSE_DEVICES',
  ADMIN_LICENSE_REVOKE_CONFIRM: 'ADMIN_LICENSE_REVOKE_CONFIRM',
  ADMIN_CREATE_LICENSE_PLAN: 'ADMIN_CREATE_LICENSE_PLAN',
  ADMIN_CREATE_LICENSE_DURATION: 'ADMIN_CREATE_LICENSE_DURATION',
  ADMIN_CREATE_LICENSE_CONFIRM: 'ADMIN_CREATE_LICENSE_CONFIRM',
  ADMIN_CREATE_LICENSE_SUCCESS: 'ADMIN_CREATE_LICENSE_SUCCESS',
  ADMIN_LANGUAGE: 'ADMIN_LANGUAGE',

  AUTH_DEEPLINK_LANGUAGE_PENDING: 'AUTH_DEEPLINK_LANGUAGE_PENDING',
  AUTH_RECOVERY: 'AUTH_RECOVERY',
  AUTH_LINK_ACCOUNT: 'AUTH_LINK_ACCOUNT',
  AUTH_LOGIN: 'AUTH_LOGIN',
} as const;

export type BotScreenId = (typeof BotScreen)[keyof typeof BotScreen];

/** Every non-root screen must have exactly one Back parent (or null for roots/terminal OTP). */
export const SCREEN_PARENT: Record<BotScreenId, BotScreenId | null> = {
  [BotScreen.USER_ROOT]: null,
  [BotScreen.USER_BUY_STANDARD]: BotScreen.USER_ROOT,
  [BotScreen.USER_BUY_PERIOD]: BotScreen.USER_BUY_STANDARD,
  [BotScreen.USER_BUY_PAYMENT_METHOD]: BotScreen.USER_BUY_PERIOD,
  [BotScreen.USER_BUY_PAYMENT_SUMMARY]: BotScreen.USER_BUY_PAYMENT_METHOD,
  [BotScreen.USER_BUY_PENDING_REENTRY]: BotScreen.USER_ROOT,
  [BotScreen.AWAITING_PAYMENT_RECEIPT]: BotScreen.USER_BUY_PAYMENT_SUMMARY,
  [BotScreen.USER_CANCEL_PAYMENT_CONFIRM]: BotScreen.AWAITING_PAYMENT_RECEIPT,
  [BotScreen.USER_LICENSES_LIST]: BotScreen.USER_ROOT,
  [BotScreen.USER_LICENSE_DETAIL]: BotScreen.USER_LICENSES_LIST,
  [BotScreen.USER_LICENSE_DEVICES]: BotScreen.USER_LICENSE_DETAIL,
  [BotScreen.USER_DEVICE_DETAIL]: BotScreen.USER_LICENSE_DEVICES,
  [BotScreen.USER_DEVICE_DISCONNECT_CONFIRM]: BotScreen.USER_DEVICE_DETAIL,
  [BotScreen.USER_RECOVERY_INSTRUCTION]: BotScreen.USER_ROOT,
  [BotScreen.USER_LANGUAGE]: BotScreen.USER_ROOT,
  [BotScreen.USER_SUPPORT_CATEGORY]: BotScreen.USER_ROOT,
  [BotScreen.SUPPORT_ACTIVE]: BotScreen.USER_SUPPORT_CATEGORY,
  [BotScreen.USER_SUPPORT_CLOSE_CONFIRM]: BotScreen.SUPPORT_ACTIVE,
  [BotScreen.USER_INSTRUCTION_ROOT]: BotScreen.USER_ROOT,
  [BotScreen.USER_INSTRUCTION_ARTICLE]: BotScreen.USER_INSTRUCTION_ROOT,

  [BotScreen.ADMIN_ROOT]: null,
  [BotScreen.ADMIN_ORDERS_LIST]: BotScreen.ADMIN_ROOT,
  [BotScreen.ADMIN_ORDER_DETAIL]: BotScreen.ADMIN_ORDERS_LIST,
  [BotScreen.ADMIN_ORDER_APPROVE_CONFIRM]: BotScreen.ADMIN_ORDER_DETAIL,
  [BotScreen.ADMIN_ORDER_REJECT_CONFIRM]: BotScreen.ADMIN_ORDER_DETAIL,
  [BotScreen.ADMIN_ORDER_REJECT_REASON]: BotScreen.ADMIN_ORDER_REJECT_CONFIRM,
  [BotScreen.ADMIN_PAYMENT_METHODS_LIST]: BotScreen.ADMIN_ROOT,
  [BotScreen.ADMIN_PAYMENT_METHOD_DETAIL]: BotScreen.ADMIN_PAYMENT_METHODS_LIST,
  [BotScreen.ADMIN_PAYMENT_METHOD_EDIT]: BotScreen.ADMIN_PAYMENT_METHODS_LIST,
  [BotScreen.ADMIN_SUPPORT_LIST]: BotScreen.ADMIN_ROOT,
  [BotScreen.ADMIN_SUPPORT_CONVERSATION]: BotScreen.ADMIN_SUPPORT_LIST,
  [BotScreen.ADMIN_SUPPORT_REPLY]: BotScreen.ADMIN_SUPPORT_CONVERSATION,
  [BotScreen.ADMIN_SUPPORT_CLOSE_CONFIRM]: BotScreen.ADMIN_SUPPORT_CONVERSATION,
  [BotScreen.ADMIN_LICENSES_LIST]: BotScreen.ADMIN_ROOT,
  [BotScreen.ADMIN_LICENSE_DETAIL]: BotScreen.ADMIN_LICENSES_LIST,
  [BotScreen.ADMIN_LICENSE_DEVICES]: BotScreen.ADMIN_LICENSE_DETAIL,
  [BotScreen.ADMIN_LICENSE_REVOKE_CONFIRM]: BotScreen.ADMIN_LICENSE_DETAIL,
  [BotScreen.ADMIN_CREATE_LICENSE_PLAN]: BotScreen.ADMIN_ROOT,
  [BotScreen.ADMIN_CREATE_LICENSE_DURATION]: BotScreen.ADMIN_CREATE_LICENSE_PLAN,
  [BotScreen.ADMIN_CREATE_LICENSE_CONFIRM]: BotScreen.ADMIN_CREATE_LICENSE_DURATION,
  [BotScreen.ADMIN_CREATE_LICENSE_SUCCESS]: BotScreen.ADMIN_LICENSES_LIST,
  [BotScreen.ADMIN_LANGUAGE]: BotScreen.ADMIN_ROOT,

  [BotScreen.AUTH_DEEPLINK_LANGUAGE_PENDING]: null,
  [BotScreen.AUTH_RECOVERY]: null,
  [BotScreen.AUTH_LINK_ACCOUNT]: null,
  [BotScreen.AUTH_LOGIN]: null,
};

export type AcceptedInput =
  | 'buttons_only'
  | 'receipt_media'
  | 'support_message'
  | 'admin_reply'
  | 'reject_reason_text'
  | 'wizard_text'
  | 'none';

export const SCREEN_INPUT: Partial<Record<BotScreenId, AcceptedInput>> = {
  [BotScreen.USER_ROOT]: 'buttons_only',
  [BotScreen.ADMIN_ROOT]: 'buttons_only',
  [BotScreen.AWAITING_PAYMENT_RECEIPT]: 'receipt_media',
  [BotScreen.SUPPORT_ACTIVE]: 'support_message',
  [BotScreen.ADMIN_SUPPORT_REPLY]: 'admin_reply',
  [BotScreen.ADMIN_ORDER_REJECT_REASON]: 'reject_reason_text',
  [BotScreen.ADMIN_PAYMENT_METHOD_EDIT]: 'wizard_text',
};

export function backParent(screen: BotScreenId): BotScreenId | null {
  return SCREEN_PARENT[screen] ?? null;
}

export function isRootScreen(screen: BotScreenId): boolean {
  return screen === BotScreen.USER_ROOT || screen === BotScreen.ADMIN_ROOT;
}

export function assertAllScreensHaveParentOrRoot(): string[] {
  const missing: string[] = [];
  for (const id of Object.values(BotScreen)) {
    if (isRootScreen(id)) continue;
    if (id.startsWith('AUTH_')) continue;
    if (SCREEN_PARENT[id] === undefined) {
      missing.push(id);
    }
  }
  return missing;
}
